
services:
  tkb-dev:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tkb-dev

    working_dir: /workspace

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "tkb.local:host-gateway"

    ports:
      - "3000:3000"
      - "3001:3001"

    user: "0:0"

    environment:
      NODE_ENV: development

      NEXT_TELEMETRY_DISABLE: "1"
      TURBO_TELEMETRY_DISABLED: "1"

      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

      PNPM_HOME: /pnpm

      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/knifestore

      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}

      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

    volumes:
      - ./:/workspace
      - pnpm_store:/pnpm/store
      - pnpm_home:/pnpm
      - ~/.gitconfig:/home/node/.gitconfig:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:ro


    tty: true
    stdin_open: true

volumes:
  pnpm_store:
  pnpm_home:

