import fs from "node:fs";
import path from "node:path";

const rootDir =
  process.cwd();

const sourcePath =
  path.join(
    rootDir,
    "config",
    "env.shared.local",
  );

const targets = [
  path.join(
    rootDir,
    "apps",
    "storefront",
    ".env.local",
  ),
  path.join(
    rootDir,
    "apps",
    "admin",
    ".env.local",
  ),
  path.join(
    rootDir,
    "apps",
    "brochure",
    ".env.local",
  ),
];

if (!fs.existsSync(sourcePath)) {
  console.error(
    `Missing source env file: ${sourcePath}`,
  );
  process.exit(1);
}

const sourceContents =
  fs.readFileSync(
    sourcePath,
    "utf8",
  );

const banner = `# GENERATED FROM /config/env.shared.local
# Do not edit this file directly.
# Run "pnpm sync:env" after updating the shared env source.

`;

const output =
  `${banner}${sourceContents.trim()}\n`;

for (const target of targets) {
  fs.writeFileSync(
    target,
    output,
    "utf8",
  );
  console.log(
    `Synced ${path.relative(rootDir, target)}`,
  );
}
